title: Sayf Essyd's Blog
email: mail.sayf@yahoo.com
description: >-
  I'm @sayfessyd, an independent software engineer. Outside of developing software, I enjoy playing the piano.
baseurl: ''
url: 'https://codebase.sayfessyd.com'

author: sayfessyd
twitter_username: sayfessyd
github_username: sayfessyd

algolia:
  application_id: 'BLHSU1VJ22'
  index_name: 'codebase'

paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - ''

# Disqus Comments
disqus:
  shortname: codebase-1
